### ISSUE TITLE
Method setDumpType does not work

### ISSUE THREAD

**Issue by riPlus** [aymanrb/MySQL-PHP-Backup-Class#1]
Method does not set the attribut.
$dumpTableFiles should be $this->dumpTableFiles

**Comment by aymanrb** [comment]
Oops! Sorry for missing this out and for my late reply. That's why having test cases even for simple classes like this should help.

I will fix it right away, thanks for the heads up :)

**Comment by aymanrb** [comment]
Should be resolved now :) thanks again.
